title: <a href="/static-analysis-course" style="color:inherit;">Static Program Analysis</a>
theme: jekyll-theme-slate

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
