title: <a href="/static-analysis-course" style="color:inherit;">Introduction to Static Analysis</a>
description: Course taught by Huawei
theme: jekyll-theme-slate

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
